const defaultTheme = {
  ltr: 'ltr',
  rtl: 'rtl',
  placeholder: 'editor-placeholder',
  paragraph: 'editor-paragraph',
  quote: 'editor-quote',
  heading: {
    h1: 'editor-heading-h1',
    h2: 'editor-heading-h2',
    h3: 'editor-heading-h3',
    h4: 'editor-heading-h4',
    h5: 'editor-heading-h5',
  },
  list: {
    nested: {
      listitem: 'editor-nested-listitem',
    },
    ol: 'editor-list-ol',
    ul: 'editor-list-ul',
    listitem: 'editor-listitem',
    olDepth: [
      'editor-list-ol1',
      'editor-list-ol2',
      'editor-list-ol3',
      'editor-list-ol4',
      'editor-list-ol5',
    ],
    ulDepth: [
      'editor-list-ul1',
      'editor-list-ul2',
      'editor-list-ul3',
      'editor-list-ul4',
      'editor-list-ul5',
    ],
    checklist: 'editor-checklist',
    listitemChecked: 'editor-listitem-checked',
    listitemUnchecked: 'editor-listitem-unchecked',
  },
  hr: 'editor-horizontal-rule',
  hrSelected: 'editor-horizontal-rule-selected',
  indent: 'editor-indent',
  image: 'editor-image',
  link: 'editor-link',
  text: {
    bold: 'editor-text-bold',
    italic: 'editor-text-italic',
    overflowed: 'editor-text-overflowed',
    hashtag: 'editor-text-hashtag',
    underline: 'editor-text-underline',
    strikethrough: 'editor-text-strikethrough',
    underlineStrikethrough: 'editor-text-underlineStrikethrough',
    code: 'editor-text-code',
  },
  code: 'editor-code',
  codeHighlight: {
    atrule: 'editor-token-attr',
    attr: 'editor-token-attr',
    boolean: 'editor-token-property',
    builtin: 'editor-token-selector',
    cdata: 'editor-token-comment',
    char: 'editor-token-selector',
    class: 'editor-token-function',
    'class-name': 'editor-token-function',
    comment: 'editor-token-comment',
    constant: 'editor-token-property',
    deleted: 'editor-token-property',
    doctype: 'editor-token-comment',
    entity: 'editor-token-operator',
    function: 'editor-token-function',
    important: 'editor-token-variable',
    inserted: 'editor-token-selector',
    keyword: 'editor-token-attr',
    namespace: 'editor-token-variable',
    number: 'editor-token-property',
    operator: 'editor-token-operator',
    prolog: 'editor-token-comment',
    property: 'editor-token-property',
    punctuation: 'editor-token-punctuation',
    regex: 'editor-token-variable',
    selector: 'editor-token-selector',
    string: 'editor-token-selector',
    symbol: 'editor-token-property',
    tag: 'editor-token-property',
    url: 'editor-token-operator',
    variable: 'editor-token-variable',
  },
  table: 'editor-table',
  tableAddColumns: 'editor-table-add-columns',
  tableAddRows: 'editor-table-add-rows',
  tableAlignment: {
    center: 'editor-table-align-center',
    right: 'editor-table-align-right',
  },
  tableCell: 'editor-table-cell',
  tableCellActionButton: 'table-cell-action-button',
  tableCellActionButtonIcon: 'table-cell-action-button-icon',
  tableCellActionButtonContainer: 'table-cell-action-button-container',
  tableCellActionButtonActiveContainer: 'table-cell-action-button-container-active',
  tableCellActionButtonInactiveContainer: 'table-cell-action-button-container-inactive',
  tableCellHeader: 'editor-table-cell-header',
  tableCellResizer: 'editor-table-cell-resizer',
  tableCellSelected: 'editor-table-cell-selected',
  tableFrozenColumn: 'editor-table-frozen-column',
  tableFrozenRow: 'editor-table-frozen-row',
  tableRowStriping: 'editor-table-row-striping',
  tableScrollableWrapper: 'editor-table-scrollable-wrapper',
  tableSelected: 'editor-table-selected',
  tableSelection: 'editor-table-selection',
  tableActionMenuDropdown: 'table-action-menu-dropdown',
  tableActionMenuItem: 'table-action-menu-item',
  equation: {
    container: 'editor-equation',
    inline: 'editor-equation-inline',
    block: 'editor-equation-block',
    renderer: 'equation-renderer',
  },
};

export default defaultTheme;
